version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwe123!!
      MYSQL_DATABASE: pessoas_db
      MYSQL_USER: pessoa
      MYSQL_PASSWORD: qwe123!!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

volumes:
  db_data:
